import type { NextPage } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { Comic } from "dh-marvel/features/card.type";
import { GridCard } from "dh-marvel/components/Card/gridCard";
import { CircularProgress, Pagination, Stack } from "@mui/material";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import { useEffect, useState } from "react";

export async function getStaticProps() {
  const response = await getComics(0, 12);
  return {
    props: {
      comics: response.data.results,
      total: response.data.total,
    },
  };
}

type props = {
  comics: Comic[];
  total: number;
};

const Index: NextPage<props> = ({ comics, total }) => {
  const [pageComic, setPageComic] = useState<Comic[]>(comics);
  const [page, setPage] = useState(1);
  // const [loading, setLoading] = useState(false);

  const getComicsApi = async (offset: number) => {
    const params = new URLSearchParams();
    params.set("offset", `${offset}`);
    params.set("limit", `${12}`);

    const response = await fetch("/api/comic?" + params.toString());
    const data = await response.json();
    // console.log(loading);
    // !data ? setLoading(true) : setLoading(false);
    setPageComic(data.comics.results);
  };

  const handleChange = (event: React.ChangeEvent<unknown>, value: number) => {
    setPage(value);
    getComicsApi(value * 12 - 12);
  };

  return (
    <>
      <Head>
        <title>DH-Marvel</title>
        <meta name="home" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodySingle title={"Comics"}>
        <Stack spacing={2} alignItems="center">
          <Pagination
            size="medium"
            count={Math.ceil(total / 12)}
            page={page}
            onChange={handleChange}
          />
        </Stack>
        <GridCard comics={pageComic} />
        <Stack spacing={2} alignItems="center">
          <Pagination
            size="medium"
            count={Math.ceil(total / 12)}
            page={page}
            onChange={handleChange}
          />
        </Stack>
      </BodySingle>
    </>
  );
};

export default Index;
